// Generated by gencpp from file place/place_data.msg
// DO NOT EDIT!


#ifndef PLACE_MESSAGE_PLACE_DATA_H
#define PLACE_MESSAGE_PLACE_DATA_H

#include <ros/service_traits.h>


#include <place/place_dataRequest.h>
#include <place/place_dataResponse.h>


namespace place
{

struct place_data
{

typedef place_dataRequest Request;
typedef place_dataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct place_data
} // namespace place


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::place::place_data > {
  static const char* value()
  {
    return "19190b8de1560dc26185b95bdbc3e5ac";
  }

  static const char* value(const ::place::place_data&) { return value(); }
};

template<>
struct DataType< ::place::place_data > {
  static const char* value()
  {
    return "place/place_data";
  }

  static const char* value(const ::place::place_data&) { return value(); }
};


// service_traits::MD5Sum< ::place::place_dataRequest> should match
// service_traits::MD5Sum< ::place::place_data >
template<>
struct MD5Sum< ::place::place_dataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::place::place_data >::value();
  }
  static const char* value(const ::place::place_dataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::place::place_dataRequest> should match
// service_traits::DataType< ::place::place_data >
template<>
struct DataType< ::place::place_dataRequest>
{
  static const char* value()
  {
    return DataType< ::place::place_data >::value();
  }
  static const char* value(const ::place::place_dataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::place::place_dataResponse> should match
// service_traits::MD5Sum< ::place::place_data >
template<>
struct MD5Sum< ::place::place_dataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::place::place_data >::value();
  }
  static const char* value(const ::place::place_dataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::place::place_dataResponse> should match
// service_traits::DataType< ::place::place_data >
template<>
struct DataType< ::place::place_dataResponse>
{
  static const char* value()
  {
    return DataType< ::place::place_data >::value();
  }
  static const char* value(const ::place::place_dataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLACE_MESSAGE_PLACE_DATA_H
