// Generated by gencpp from file place/place_dataRequest.msg
// DO NOT EDIT!


#ifndef PLACE_MESSAGE_PLACE_DATAREQUEST_H
#define PLACE_MESSAGE_PLACE_DATAREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace place
{
template <class ContainerAllocator>
struct place_dataRequest_
{
  typedef place_dataRequest_<ContainerAllocator> Type;

  place_dataRequest_()
    : pose()
    , id(0)  {
    }
  place_dataRequest_(const ContainerAllocator& _alloc)
    : pose(_alloc)
    , id(0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef int64_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::place::place_dataRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::place::place_dataRequest_<ContainerAllocator> const> ConstPtr;

}; // struct place_dataRequest_

typedef ::place::place_dataRequest_<std::allocator<void> > place_dataRequest;

typedef boost::shared_ptr< ::place::place_dataRequest > place_dataRequestPtr;
typedef boost::shared_ptr< ::place::place_dataRequest const> place_dataRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::place::place_dataRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::place::place_dataRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::place::place_dataRequest_<ContainerAllocator1> & lhs, const ::place::place_dataRequest_<ContainerAllocator2> & rhs)
{
  return lhs.pose == rhs.pose &&
    lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::place::place_dataRequest_<ContainerAllocator1> & lhs, const ::place::place_dataRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace place

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::place::place_dataRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::place::place_dataRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::place::place_dataRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::place::place_dataRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::place::place_dataRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::place::place_dataRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::place::place_dataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f9c916a840e4b0047e6edf6fcd86ffa8";
  }

  static const char* value(const ::place::place_dataRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf9c916a840e4b004ULL;
  static const uint64_t static_value2 = 0x7e6edf6fcd86ffa8ULL;
};

template<class ContainerAllocator>
struct DataType< ::place::place_dataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "place/place_dataRequest";
  }

  static const char* value(const ::place::place_dataRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::place::place_dataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose pose\n"
"int64 id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::place::place_dataRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::place::place_dataRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct place_dataRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::place::place_dataRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::place::place_dataRequest_<ContainerAllocator>& v)
  {
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLACE_MESSAGE_PLACE_DATAREQUEST_H
