// Generated by gencpp from file astar/GoToPosResponse.msg
// DO NOT EDIT!


#ifndef ASTAR_MESSAGE_GOTOPOSRESPONSE_H
#define ASTAR_MESSAGE_GOTOPOSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace astar
{
template <class ContainerAllocator>
struct GoToPosResponse_
{
  typedef GoToPosResponse_<ContainerAllocator> Type;

  GoToPosResponse_()
    : result(false)  {
    }
  GoToPosResponse_(const ContainerAllocator& _alloc)
    : result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::astar::GoToPosResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::astar::GoToPosResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GoToPosResponse_

typedef ::astar::GoToPosResponse_<std::allocator<void> > GoToPosResponse;

typedef boost::shared_ptr< ::astar::GoToPosResponse > GoToPosResponsePtr;
typedef boost::shared_ptr< ::astar::GoToPosResponse const> GoToPosResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::astar::GoToPosResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::astar::GoToPosResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::astar::GoToPosResponse_<ContainerAllocator1> & lhs, const ::astar::GoToPosResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::astar::GoToPosResponse_<ContainerAllocator1> & lhs, const ::astar::GoToPosResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace astar

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::astar::GoToPosResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::astar::GoToPosResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::astar::GoToPosResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::astar::GoToPosResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::astar::GoToPosResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::astar::GoToPosResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::astar::GoToPosResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::astar::GoToPosResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::astar::GoToPosResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "astar/GoToPosResponse";
  }

  static const char* value(const ::astar::GoToPosResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::astar::GoToPosResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"bool result\n"
;
  }

  static const char* value(const ::astar::GoToPosResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::astar::GoToPosResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoToPosResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::astar::GoToPosResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::astar::GoToPosResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASTAR_MESSAGE_GOTOPOSRESPONSE_H
