// Generated by gencpp from file astar/GoToPos.msg
// DO NOT EDIT!


#ifndef ASTAR_MESSAGE_GOTOPOS_H
#define ASTAR_MESSAGE_GOTOPOS_H

#include <ros/service_traits.h>


#include <astar/GoToPosRequest.h>
#include <astar/GoToPosResponse.h>


namespace astar
{

struct GoToPos
{

typedef GoToPosRequest Request;
typedef GoToPosResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GoToPos
} // namespace astar


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::astar::GoToPos > {
  static const char* value()
  {
    return "c4572a94d2113bac1ddcbfd514e67b1a";
  }

  static const char* value(const ::astar::GoToPos&) { return value(); }
};

template<>
struct DataType< ::astar::GoToPos > {
  static const char* value()
  {
    return "astar/GoToPos";
  }

  static const char* value(const ::astar::GoToPos&) { return value(); }
};


// service_traits::MD5Sum< ::astar::GoToPosRequest> should match
// service_traits::MD5Sum< ::astar::GoToPos >
template<>
struct MD5Sum< ::astar::GoToPosRequest>
{
  static const char* value()
  {
    return MD5Sum< ::astar::GoToPos >::value();
  }
  static const char* value(const ::astar::GoToPosRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::astar::GoToPosRequest> should match
// service_traits::DataType< ::astar::GoToPos >
template<>
struct DataType< ::astar::GoToPosRequest>
{
  static const char* value()
  {
    return DataType< ::astar::GoToPos >::value();
  }
  static const char* value(const ::astar::GoToPosRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::astar::GoToPosResponse> should match
// service_traits::MD5Sum< ::astar::GoToPos >
template<>
struct MD5Sum< ::astar::GoToPosResponse>
{
  static const char* value()
  {
    return MD5Sum< ::astar::GoToPos >::value();
  }
  static const char* value(const ::astar::GoToPosResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::astar::GoToPosResponse> should match
// service_traits::DataType< ::astar::GoToPos >
template<>
struct DataType< ::astar::GoToPosResponse>
{
  static const char* value()
  {
    return DataType< ::astar::GoToPos >::value();
  }
  static const char* value(const ::astar::GoToPosResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASTAR_MESSAGE_GOTOPOS_H
