// Generated by gencpp from file object_detection/get_object_poseRequest.msg
// DO NOT EDIT!


#ifndef OBJECT_DETECTION_MESSAGE_GET_OBJECT_POSEREQUEST_H
#define OBJECT_DETECTION_MESSAGE_GET_OBJECT_POSEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace object_detection
{
template <class ContainerAllocator>
struct get_object_poseRequest_
{
  typedef get_object_poseRequest_<ContainerAllocator> Type;

  get_object_poseRequest_()
    {
    }
  get_object_poseRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::object_detection::get_object_poseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::object_detection::get_object_poseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct get_object_poseRequest_

typedef ::object_detection::get_object_poseRequest_<std::allocator<void> > get_object_poseRequest;

typedef boost::shared_ptr< ::object_detection::get_object_poseRequest > get_object_poseRequestPtr;
typedef boost::shared_ptr< ::object_detection::get_object_poseRequest const> get_object_poseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::object_detection::get_object_poseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::object_detection::get_object_poseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace object_detection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::object_detection::get_object_poseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_detection::get_object_poseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_detection::get_object_poseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_detection::get_object_poseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_detection::get_object_poseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_detection::get_object_poseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::object_detection::get_object_poseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::object_detection::get_object_poseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::object_detection::get_object_poseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "object_detection/get_object_poseRequest";
  }

  static const char* value(const ::object_detection::get_object_poseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::object_detection::get_object_poseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::object_detection::get_object_poseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::object_detection::get_object_poseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct get_object_poseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::object_detection::get_object_poseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::object_detection::get_object_poseRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // OBJECT_DETECTION_MESSAGE_GET_OBJECT_POSEREQUEST_H
