// Generated by gencpp from file camera_rotation/find_plateResponse.msg
// DO NOT EDIT!


#ifndef CAMERA_ROTATION_MESSAGE_FIND_PLATERESPONSE_H
#define CAMERA_ROTATION_MESSAGE_FIND_PLATERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace camera_rotation
{
template <class ContainerAllocator>
struct find_plateResponse_
{
  typedef find_plateResponse_<ContainerAllocator> Type;

  find_plateResponse_()
    : result()
    , pose()  {
    }
  find_plateResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _result_type;
  _result_type result;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::camera_rotation::find_plateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::camera_rotation::find_plateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct find_plateResponse_

typedef ::camera_rotation::find_plateResponse_<std::allocator<void> > find_plateResponse;

typedef boost::shared_ptr< ::camera_rotation::find_plateResponse > find_plateResponsePtr;
typedef boost::shared_ptr< ::camera_rotation::find_plateResponse const> find_plateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::camera_rotation::find_plateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::camera_rotation::find_plateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::camera_rotation::find_plateResponse_<ContainerAllocator1> & lhs, const ::camera_rotation::find_plateResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::camera_rotation::find_plateResponse_<ContainerAllocator1> & lhs, const ::camera_rotation::find_plateResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace camera_rotation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::camera_rotation::find_plateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::camera_rotation::find_plateResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_rotation::find_plateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_rotation::find_plateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_rotation::find_plateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_rotation::find_plateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::camera_rotation::find_plateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e3c18ef4e2552236a5066550b0b32eee";
  }

  static const char* value(const ::camera_rotation::find_plateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe3c18ef4e2552236ULL;
  static const uint64_t static_value2 = 0xa5066550b0b32eeeULL;
};

template<class ContainerAllocator>
struct DataType< ::camera_rotation::find_plateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "camera_rotation/find_plateResponse";
  }

  static const char* value(const ::camera_rotation::find_plateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::camera_rotation::find_plateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string result\n"
"geometry_msgs/PoseStamped pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::camera_rotation::find_plateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::camera_rotation::find_plateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct find_plateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::camera_rotation::find_plateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::camera_rotation::find_plateResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.result);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMERA_ROTATION_MESSAGE_FIND_PLATERESPONSE_H
