// Generated by gencpp from file grasp/data.msg
// DO NOT EDIT!


#ifndef GRASP_MESSAGE_DATA_H
#define GRASP_MESSAGE_DATA_H

#include <ros/service_traits.h>


#include <grasp/dataRequest.h>
#include <grasp/dataResponse.h>


namespace grasp
{

struct data
{

typedef dataRequest Request;
typedef dataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct data
} // namespace grasp


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::grasp::data > {
  static const char* value()
  {
    return "19190b8de1560dc26185b95bdbc3e5ac";
  }

  static const char* value(const ::grasp::data&) { return value(); }
};

template<>
struct DataType< ::grasp::data > {
  static const char* value()
  {
    return "grasp/data";
  }

  static const char* value(const ::grasp::data&) { return value(); }
};


// service_traits::MD5Sum< ::grasp::dataRequest> should match
// service_traits::MD5Sum< ::grasp::data >
template<>
struct MD5Sum< ::grasp::dataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::grasp::data >::value();
  }
  static const char* value(const ::grasp::dataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::grasp::dataRequest> should match
// service_traits::DataType< ::grasp::data >
template<>
struct DataType< ::grasp::dataRequest>
{
  static const char* value()
  {
    return DataType< ::grasp::data >::value();
  }
  static const char* value(const ::grasp::dataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::grasp::dataResponse> should match
// service_traits::MD5Sum< ::grasp::data >
template<>
struct MD5Sum< ::grasp::dataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::grasp::data >::value();
  }
  static const char* value(const ::grasp::dataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::grasp::dataResponse> should match
// service_traits::DataType< ::grasp::data >
template<>
struct DataType< ::grasp::dataResponse>
{
  static const char* value()
  {
    return DataType< ::grasp::data >::value();
  }
  static const char* value(const ::grasp::dataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GRASP_MESSAGE_DATA_H
